
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Janela.java
 *
 * Created on 02/04/2011, 12:57:04
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.JFileChooser;

/**
 *
 * @author Everton
 */
public class Janela extends javax.swing.JFrame {

    private Erro erro;
    private String textoFonte;
    private StringBuilder textoMepa;
    private StringBuilder textoSaida;
    private ThreadExecucao threadexecucao;

    /** Creates new form Janela */
    public Janela() {
        initComponents();
        this.setLocation(683 - (this.getWidth() / 2), (384 - ((this.getHeight() / 2) + 50)));
        this.jTAFonte.setText("program exemplo;\nvar a : integer;\nbegin\n   read(a);\n   write(a);\nend.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Compila = new javax.swing.JButton();
        Executa = new javax.swing.JButton();
        Termina = new javax.swing.JButton();
        jSPFonte = new javax.swing.JScrollPane();
        jTAFonte = new javax.swing.JTextArea();
        jSPMepa = new javax.swing.JScrollPane();
        jTAMepa = new javax.swing.JTextArea();
        jSPSaida = new javax.swing.JScrollPane();
        jTASaida = new javax.swing.JTextArea();
        jBAbrirArquivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador Pascal");
        setFont(new java.awt.Font("Arial", 0, 10));

        Compila.setText("Compila");
        Compila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompilaActionPerformed(evt);
            }
        });

        Executa.setText("Executa");
        Executa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutaActionPerformed(evt);
            }
        });

        Termina.setText("Termina");
        Termina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminaActionPerformed(evt);
            }
        });

        jSPFonte.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Fonte"));

        jTAFonte.setColumns(20);
        jTAFonte.setRows(5);
        jSPFonte.setViewportView(jTAFonte);

        jSPMepa.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Mepa"));

        jTAMepa.setColumns(20);
        jTAMepa.setRows(5);
        jSPMepa.setViewportView(jTAMepa);

        jSPSaida.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Saida"));

        jTASaida.setColumns(20);
        jTASaida.setEditable(false);
        jTASaida.setRows(5);
        jSPSaida.setViewportView(jTASaida);

        jBAbrirArquivo.setText("Abrir Arquivo");
        jBAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jSPFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSPMepa))
                            .addComponent(jSPSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jBAbrirArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Compila, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Executa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Termina, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAbrirArquivo)
                    .addComponent(Compila)
                    .addComponent(Executa)
                    .addComponent(Termina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSPMepa, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jSPFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompilaActionPerformed

        try {
            this.erro = new Erro(0, 0);
            this.jTAFonte.getText();
            this.textoFonte = this.jTAFonte.getText();
            this.textoMepa = new StringBuilder("");
            this.textoSaida = new StringBuilder("");
            sintatico p = new sintatico(new StringReader(textoFonte), textoMepa, textoSaida, erro);
            Object result = p.parse().value;
            this.jTAMepa.setText(textoMepa.toString());
            if (erro.colErro() == 0) {
                textoSaida.append("Programa correto!\n");
            } else {
                this.jTAFonte.setText(textoFonte);
                this.jTAFonte.select(erro.linErro() - 1, erro.linErro());
            }
            this.jTASaida.setText(textoSaida.toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_CompilaActionPerformed

    private void ExecutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutaActionPerformed

        if (erro.colErro() == 0) {
            threadexecucao = new ThreadExecucao(textoMepa, jTASaida);
            threadexecucao.start();
        }

    }//GEN-LAST:event_ExecutaActionPerformed

    private void TerminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminaActionPerformed

        if (threadexecucao != null) {
            threadexecucao.para();
        }

    }//GEN-LAST:event_TerminaActionPerformed

    private void jBAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirArquivoActionPerformed
        JFileChooser fc = new JFileChooser();
        File file;
        String str, texto = "";
        int res;

        try {
            res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File arquivo = fc.getSelectedFile();
                jTAFonte.setText("");

                try {
                    BufferedReader in = new BufferedReader(new FileReader(arquivo));                   
                    while ((str = in.readLine()) != null) {
                        texto += str + "\n";
                    }
                    jTAFonte.setText(texto);
                    in.close();
                } catch (IOException ioe) {
                    System.out.println(ioe.getMessage());
                }
            }

        } catch (Exception ex) {
            System.out.println("Nenhum Arquivo foi aberto!");
        }
    }//GEN-LAST:event_jBAbrirArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Compila;
    public javax.swing.JButton Executa;
    public javax.swing.JButton Termina;
    private javax.swing.JButton jBAbrirArquivo;
    public javax.swing.JScrollPane jSPFonte;
    public javax.swing.JScrollPane jSPMepa;
    public javax.swing.JScrollPane jSPSaida;
    public javax.swing.JTextArea jTAFonte;
    public javax.swing.JTextArea jTAMepa;
    public javax.swing.JTextArea jTASaida;
    // End of variables declaration//GEN-END:variables
}
