
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 08 22:27:00 BRT 2011
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int S_DO = 33;
  public static final int S_VIRGULA = 11;
  public static final int S_END = 28;
  public static final int S_DIFERENTE = 2;
  public static final int S_VEZES = 21;
  public static final int S_MAIS = 26;
  public static final int S_VAR = 27;
  public static final int S_PROGRAM = 8;
  public static final int S_OR = 34;
  public static final int S_WRITE = 15;
  public static final int EOF = 0;
  public static final int S_PONTO = 22;
  public static final int S_IF = 32;
  public static final int error = 1;
  public static final int S_IGUAL = 19;
  public static final int S_ELSE = 25;
  public static final int S_FECHAPAR = 4;
  public static final int S_ABREPAR = 10;
  public static final int S_READ = 16;
  public static final int S_NOT = 31;
  public static final int S_AND = 30;
  public static final int S_BEGIN = 23;
  public static final int S_UNTIL = 36;
  public static final int S_THEN = 24;
  public static final int S_DOISPTOS = 3;
  public static final int S_DIV = 29;
  public static final int S_ATRIBUI = 12;
  public static final int S_MAIOR = 17;
  public static final int S_NUMERO = 13;
  public static final int S_MENOS = 20;
  public static final int S_MENOR = 18;
  public static final int S_MAIGUAL = 6;
  public static final int S_REPEAT = 35;
  public static final int S_IDENTIF = 37;
  public static final int S_MEIGUAL = 7;
  public static final int S_PONTOVG = 9;
  public static final int S_PROCEDURE = 5;
  public static final int S_WHILE = 14;
}

