
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 15 14:37:04 BRT 2011
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int S_DO = 34;
  public static final int S_VIRGULA = 12;
  public static final int S_END = 29;
  public static final int S_DIFERENTE = 2;
  public static final int S_VEZES = 22;
  public static final int S_MAIS = 27;
  public static final int S_VAR = 28;
  public static final int S_PROGRAM = 9;
  public static final int S_OR = 35;
  public static final int S_WRITE = 16;
  public static final int EOF = 0;
  public static final int S_PONTO = 23;
  public static final int S_IF = 33;
  public static final int error = 1;
  public static final int S_IGUAL = 20;
  public static final int S_ELSE = 26;
  public static final int S_FECHAPAR = 4;
  public static final int S_ABREPAR = 11;
  public static final int S_READ = 17;
  public static final int S_NOT = 32;
  public static final int S_AND = 31;
  public static final int S_BEGIN = 24;
  public static final int S_UNTIL = 37;
  public static final int S_THEN = 25;
  public static final int S_DOISPTOS = 3;
  public static final int S_DIV = 30;
  public static final int S_ATRIBUI = 13;
  public static final int S_MAIOR = 18;
  public static final int S_NUMERO = 14;
  public static final int S_FUNCTION = 6;
  public static final int S_MENOS = 21;
  public static final int S_MENOR = 19;
  public static final int S_MAIGUAL = 7;
  public static final int S_REPEAT = 36;
  public static final int S_IDENTIF = 38;
  public static final int S_MEIGUAL = 8;
  public static final int S_PONTOVG = 10;
  public static final int S_PROCEDURE = 5;
  public static final int S_WHILE = 15;
}

